services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./app/public:/var/www/html
      - ./app/private:/var/www/private
    environment:
      - APP_ENV=dev
      - API_ALLOWLIST=api.github.com
